#!/bin/bash

# author Ian Flanagan
# it randomly gets a list of all items and then will resolve 1 random item

mytoken=$1
myItemsList=itemslists
myItemsFile=items
newFile=newcommand
myConfigFile=command

echo "Resolving items now"

rm -rf $myItemsFile $myItemsList $myConfigFile $newFile

curl -H "X-Rollbar-Access-Token: $mytoken" 'https://api.rollbar.com/api/1/items/?status=active' | tee $myItemsFile
cat $myItemsFile | grep '"id":' | awk '{print $2}' | sed 's/,/ /g' > $myItemsList

  # pick a random item from the list
  # get num of file lines
  filelength=$(cat $myItemsList | wc -l)
  # generate a random number between 1 and the num of lines in the file
  number=$(( ( RANDOM % $filelength )  + 1 ))
  # obtain the item
  item=$(cat $myItemsList | head -$number | tail -1)
  echo $item > $newFile

# for i in `cat $myItemsList`
for i in `cat $newFile`
do
echo "Resolving item: " $i " using token:" $mytoken

echo "https://api.rollbar.com/api/1/item/$i"
#curl -H \"X-Rollbar-Access-Token: $mytoken\" \ -X GET 'https://api.rollbar.com/api/1/item/$i'

echo "curl -H \"X-Rollbar-Access-Token: $mytoken\" \
-H \"Content-Type: application/json\" -X PATCH  'https://api.rollbar.com/api/1/item/$i' \
--data '{\"status\": \"resolved\"}'" >> $myConfigFile
echo "" >> $myConfigFile

# delete all occurences 
#curl -H "X-Rollbar-Access-Token: $mytoken" \
#-H "Content-Type: application/json" -X PATCH  'https://api.rollbar.com/api/1/item/$i' \
#--data '{"status": "resolved"}'

done

chmod 755 $myConfigFile
./$myConfigFile
